language: node_js
env: CI=true
node_js:
  - stable
before_script:
  - npm install -g gulp
script: 
  - gulp
  - node ./bin/sally verify *.sal -s xyzzy
  - pkg=$(npm pack)
  - npm install -g $pkg
  - (cd ~ && sally)
  