language: node_js
env: CI=true
node_js:
  - stable
before_script:
  - npm install -g gulp
  - chmod +x ./test/npm-test.sh
script: 
  - gulp
  - node ./sally.js verify *.sal -s xyzzy
  - pkg=$(npm pack)
  - npm install -g $pkg
  - (cd ~ && sally)
  