language: node_js
env: CI=true
node_js:
  - stable
before_script:
  - npm install -g gulp
  - chmod +x ./test/npm-test.sh
script: 
  - gulp
  - node ./src/sally-cli.js verify *.sal -s xyzzy
  - ./test/npm-test.sh
